<script>
    import { Table, TableBody, TableBodyCell, TableBodyRow, TableHead, TableHeadCell, Checkbox } from 'flowbite-svelte';
  </script>
  
  <Table color="green">
    <TableHead>
        <TableHeadCell></TableHeadCell>
        <TableHeadCell>Oct-24</TableHeadCell>
        <TableHeadCell>Nov-24</TableHeadCell>
        <TableHeadCell>Dec-24</TableHeadCell>
        <TableHeadCell>Jan-25</TableHeadCell>
        <TableHeadCell>Feb-25</TableHeadCell>
        <TableHeadCell>Mar-25</TableHeadCell>
        <TableHeadCell>Apr-25</TableHeadCell>
        <TableHeadCell>May-25</TableHeadCell>
        <TableHeadCell>Jun-25</TableHeadCell>
        <TableHeadCell>Jul-25</TableHeadCell>
        <TableHeadCell>Aug-25</TableHeadCell>
        <TableHeadCell>Sep-25</TableHeadCell>
        <TableHeadCell>Oct-25</TableHeadCell>
        <TableHeadCell>Nov-25</TableHeadCell>
        <TableHeadCell>Dec-25</TableHeadCell>
    </TableHead>
    <TableBody tableBodyClass="divide-y">
      <TableBodyRow>
        <TableBodyCell>Avanço de obra mensal</TableBodyCell>
        <TableBodyCell>16%</TableBodyCell>
        <TableBodyCell>10%</TableBodyCell>
        <TableBodyCell>11%</TableBodyCell>
        <TableBodyCell>9%</TableBodyCell>
        <TableBodyCell>9%</TableBodyCell>
        <TableBodyCell>8%</TableBodyCell>
        <TableBodyCell>7%</TableBodyCell>
        <TableBodyCell>5%</TableBodyCell>
        <TableBodyCell>4%</TableBodyCell>
        <TableBodyCell>4%</TableBodyCell>
        <TableBodyCell>4%</TableBodyCell>
        <TableBodyCell>4%</TableBodyCell>
        <TableBodyCell>4%</TableBodyCell>
        <TableBodyCell>3%</TableBodyCell>
        <TableBodyCell>2%</TableBodyCell>
      </TableBodyRow>
      <TableBodyRow>
        <TableBodyCell>Receita mensal (R$)</TableBodyCell>
        <TableBodyCell>1,231,153.47</TableBodyCell>
        <TableBodyCell>714,762.09</TableBodyCell>
        <TableBodyCell>823,286.17</TableBodyCell>
        <TableBodyCell>673,597.78</TableBodyCell>
        <TableBodyCell>673,597.78</TableBodyCell>
        <TableBodyCell>598,753.58</TableBodyCell>
        <TableBodyCell>523,909.38</TableBodyCell>
        <TableBodyCell>374,220.99</TableBodyCell>
        <TableBodyCell>299,376.79</TableBodyCell>
        <TableBodyCell>299,376.79</TableBodyCell>
        <TableBodyCell>299,376.79</TableBodyCell>
        <TableBodyCell>299,376.79</TableBodyCell>
        <TableBodyCell>299,376.79</TableBodyCell>
        <TableBodyCell>224,532.59</TableBodyCell>
        <TableBodyCell>149,721.97</TableBodyCell>
      </TableBodyRow>
      <TableBodyRow>
        <TableBodyCell>Avanço de obra mensal</TableBodyCell>
        <TableBodyCell>24%</TableBodyCell>
        <TableBodyCell>8%</TableBodyCell>
        <TableBodyCell>9%</TableBodyCell>
        <TableBodyCell>8%</TableBodyCell>
        <TableBodyCell>8%</TableBodyCell>
        <TableBodyCell>7%</TableBodyCell>
        <TableBodyCell>6%</TableBodyCell>
        <TableBodyCell>5%</TableBodyCell>
        <TableBodyCell>4%</TableBodyCell>
        <TableBodyCell>4%</TableBodyCell>
        <TableBodyCell>4%</TableBodyCell>
        <TableBodyCell>4%</TableBodyCell>
        <TableBodyCell>4%</TableBodyCell>
        <TableBodyCell>3%</TableBodyCell>
        <TableBodyCell>2%</TableBodyCell>
      </TableBodyRow>
      <TableBodyRow>
        <TableBodyCell>Avanço de obra acumulado</TableBodyCell>
        <TableBodyCell></TableBodyCell>
        <TableBodyCell>32%</TableBodyCell>
        <TableBodyCell>41%</TableBodyCell>
        <TableBodyCell>49%</TableBodyCell>
        <TableBodyCell>57%</TableBodyCell>
        <TableBodyCell>64%</TableBodyCell>
        <TableBodyCell>70%</TableBodyCell>
        <TableBodyCell>75%</TableBodyCell>
        <TableBodyCell>79%</TableBodyCell>
        <TableBodyCell>83%</TableBodyCell>
        <TableBodyCell>87%</TableBodyCell>
        <TableBodyCell>91%</TableBodyCell>
        <TableBodyCell>95%</TableBodyCell>
        <TableBodyCell>98%</TableBodyCell>
        <TableBodyCell>100.000%</TableBodyCell>
      </TableBodyRow>
      <TableBodyRow>
        <TableBodyCell>Custo mensal (R$)</TableBodyCell>
        <TableBodyCell>975,019.17</TableBodyCell>
        <TableBodyCell>323,333.73</TableBodyCell>
        <TableBodyCell>363,750.45</TableBodyCell>
        <TableBodyCell>323,333.73</TableBodyCell>
        <TableBodyCell>323,333.73</TableBodyCell>
        <TableBodyCell>282,917.02</TableBodyCell>
        <TableBodyCell>242,500.30</TableBodyCell>
        <TableBodyCell>202,083.58</TableBodyCell>
        <TableBodyCell>161,666.87</TableBodyCell>
        <TableBodyCell>161,666.87</TableBodyCell>
        <TableBodyCell>161,666.87</TableBodyCell>
        <TableBodyCell>161,666.87</TableBodyCell>
        <TableBodyCell>161,666.87</TableBodyCell>
        <TableBodyCell>121,250.15</TableBodyCell>
        <TableBodyCell>75,815.46</TableBodyCell>
      </TableBodyRow>
      <TableBodyRow>
        <TableBodyCell>Geração de Caixa Mensal (R$)</TableBodyCell>
        <TableBodyCell></TableBodyCell>
        <TableBodyCell>391,428.35</TableBodyCell>
        <TableBodyCell>459,535.72</TableBodyCell>
        <TableBodyCell>350,264.04</TableBodyCell>
        <TableBodyCell>350,264.04</TableBodyCell>
        <TableBodyCell>315,836.56</TableBodyCell>
        <TableBodyCell>281,409.08</TableBodyCell>
        <TableBodyCell>172,137.40</TableBodyCell>
        <TableBodyCell>137,709.92</TableBodyCell>
        <TableBodyCell>137,709.92</TableBodyCell>
        <TableBodyCell>137,709.92</TableBodyCell>
        <TableBodyCell>137,709.92</TableBodyCell>
        <TableBodyCell>137,709.92</TableBodyCell>
        <TableBodyCell>103,282.44</TableBodyCell>
        <TableBodyCell>73,906.51</TableBodyCell>
      </TableBodyRow>
      <TableBodyRow>
        <TableBodyCell>Geração de Caixa Acumulado (R$)</TableBodyCell>
        <TableBodyCell>256,134.30</TableBodyCell>
        <TableBodyCell>647,562.65</TableBodyCell>
        <TableBodyCell>1,107,098.37</TableBodyCell>
        <TableBodyCell>1,457,362.42</TableBodyCell>
        <TableBodyCell>1,807,626.46</TableBodyCell>
        <TableBodyCell>2,123,463.02</TableBodyCell>
        <TableBodyCell>2,404,872.10</TableBodyCell>
        <TableBodyCell>2,577,009.51</TableBodyCell>
        <TableBodyCell>2,714,719.43</TableBodyCell>
        <TableBodyCell>2,852,429.35</TableBodyCell>
        <TableBodyCell>2,990,139.28</TableBodyCell>
        <TableBodyCell>3,127,849.20</TableBodyCell>
        <TableBodyCell>3,265,559.12</TableBodyCell>
        <TableBodyCell>3,368,841.56</TableBodyCell>
        <TableBodyCell>3,442,748.07</TableBodyCell>
      </TableBodyRow>
    </TableBody>
  </Table>